# Generated by Django 2.2.3 on 2020-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0050_auto_20200406_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='avilable_work',
            name='job_id',
            field=models.IntegerField(default=0),
        ),
    ]
